## Phase II Preparation:
+ This notebook is where we prepare the raw normalized expression data from [GSE252168 Study](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE252168) to be used for Information Gain (IG) calculation in Phase II. In the part 2 of this notebooks, we also prepare a dataframe where patient IDs are mapped to their corresponding health status (Control vs Lung Cancer) to later be used for IG calculation as well.

## Part 1: Prepare the normalized-raw expression matrix to Information Gain (Phase II)
+ Normalized-raw expression dataset of our study stored as [GSE252168_Matrix_normalized](../data/GSE252168/GSE252168_Matrix_normalized.txt) in the data folder.
+ Filtered DEA results from Phase I is stored as [dea_filtered](../data/GSE252168/dea_filtered.tsv) in the data folder.

In [128]:
import pandas as pd

In [2]:
# Get IDs from DEA filtered dataset to use filter my raw expression data
dea_filt = pd.read_csv("../data/GSE252168/dea_filtered.tsv", sep="\t", usecols=[0])
print(dea_filt.shape)
dea_filt.head()

(14044, 1)

             ID
0  ILMN_1769409
1  ILMN_1762769
2  ILMN_1750507
3  ILMN_1754195
4  ILMN_1787949

In [3]:
# Get only IDs
id_dea = dea_filt["ID"].to_list()
print(len(id_dea))
print(id_dea)

14044

In [ ]:
# Upload raw & Normalized expression data from GEO
raw_norm = pd.read_csv("../data/GSE252168/GSE252168_Matrix_normalized.txt", sep="\t")
print(raw_norm.shape)
raw_norm.head()

(30715, 607)

,ID_REF,HUNT_1,Detection Pval,HUNT_10,Detection Pval.1,HUNT_100,Detection Pval.2,HUNT_101,Detection Pval.3,HUNT_102,...,401_00284,Detection Pval.298,401_00293,Detection Pval.299,401_00302_mPT,Detection Pval.300,401_00304_mPT,Detection Pval.301,401_00309,Detection Pval.302
0,ILMN_1762337,6.601397,0.14156,6.477026,0.60909,6.528409,0.38182,6.547416,0.34675,6.623571,...,6.595165,0.21169,6.567500,0.38442,6.603265,0.30649,6.594202,0.28961,6.484851,0.62208
1,ILMN_2055271,6.772395,0.01948,6.680842,0.19481,6.667478,0.16234,6.732711,0.08831,6.848822,...,6.600048,0.20000,6.762610,0.02078,6.914707,0.00779,6.702210,0.05584,6.704940,0.03636
2,ILMN_1736007,6.555132,0.24416,6.640189,0.08442,6.500988,0.42987,6.509216,0.42727,6.498857,...,6.527477,0.42987,6.547211,0.46883,6.563996,0.43636,6.512566,0.56623,6.666084,0.08442
3,ILMN_2383229,6.563006,0.31688,6.738270,0.02987,6.645548,0.09091,6.628310,0.16234,6.607876,...,6.644783,0.08571,6.790839,0.01429,6.644506,0.20519,6.550283,0.44156,6.633126,0.14805
4,ILMN_1806310,6.647101,0.18701,6.649058,0.22338,6.711497,0.04545,6.675631,0.14416,6.615123,...,6.691244,0.02078,6.497731,0.63896,6.578981,0.38831,6.821148,0.00909,6.629574,0.15455

In [ ]:
# Filtered normalized raw data via genes coming from DEA
raw_filt = raw_norm[raw_norm["ID_REF"].isin(id_dea)].copy()
print(raw_filt.shape)
raw_filt.head()

(14044, 607)

,ID_REF,HUNT_1,Detection Pval,HUNT_10,Detection Pval.1,HUNT_100,Detection Pval.2,HUNT_101,Detection Pval.3,HUNT_102,...,401_00284,Detection Pval.298,401_00293,Detection Pval.299,401_00302_mPT,Detection Pval.300,401_00304_mPT,Detection Pval.301,401_00309,Detection Pval.302
0,ILMN_1762337,6.601397,0.14156,6.477026,0.60909,6.528409,0.38182,6.547416,0.34675,6.623571,...,6.595165,0.21169,6.567500,0.38442,6.603265,0.30649,6.594202,0.28961,6.484851,0.62208
2,ILMN_1736007,6.555132,0.24416,6.640189,0.08442,6.500988,0.42987,6.509216,0.42727,6.498857,...,6.527477,0.42987,6.547211,0.46883,6.563996,0.43636,6.512566,0.56623,6.666084,0.08442
3,ILMN_2383229,6.563006,0.31688,6.738270,0.02987,6.645548,0.09091,6.628310,0.16234,6.607876,...,6.644783,0.08571,6.790839,0.01429,6.644506,0.20519,6.550283,0.44156,6.633126,0.14805
7,ILMN_1814316,6.538115,0.33506,6.554947,0.32468,6.461470,0.59870,6.569797,0.27013,6.574199,...,6.653920,0.06753,6.601662,0.25844,6.522618,0.57273,6.550283,0.44026,6.511778,0.52338
9,ILMN_1668111,6.487908,0.15455,6.451093,0.31039,6.333161,0.64675,6.313699,0.72208,6.391719,...,6.596334,0.21039,6.409157,0.82468,6.633256,0.22208,6.667974,0.10260,6.515780,0.50519

In [ ]:
# Get column names not containing Detection phrase since we only need gene expression values
new_cols = raw_filt.columns[~raw_filt.columns.str.contains("Detection")]

# Filter normalized row dataset for only patient (control & cancer) expression columns
row_filt2 = raw_filt[new_cols].copy()
print(row_filt2.shape)
row_filt2.head()

(14044, 304)

,ID_REF,HUNT_1,HUNT_10,HUNT_100,HUNT_101,HUNT_102,HUNT_103,HUNT_104,HUNT_105,HUNT_106,...,401_00271_mPT,401_00273,401_00274,401_00276,401_00278,401_00284,401_00293,401_00302_mPT,401_00304_mPT,401_00309
0,ILMN_1762337,6.601397,6.477026,6.528409,6.547416,6.623571,6.553632,6.611564,7.098132,6.615111,...,6.571935,6.616574,6.647890,6.648421,6.695155,6.595165,6.567500,6.603265,6.594202,6.484851
2,ILMN_1736007,6.555132,6.640189,6.500988,6.509216,6.498857,6.477228,6.500019,6.741477,6.611347,...,6.412316,6.543447,6.482089,6.477255,6.541832,6.527477,6.547211,6.563996,6.512566,6.666084
3,ILMN_2383229,6.563006,6.738270,6.645548,6.628310,6.607876,6.593980,6.526462,6.650312,6.624751,...,6.497549,6.718409,6.585056,6.563896,6.654124,6.644783,6.790839,6.644506,6.550283,6.633126
7,ILMN_1814316,6.538115,6.554947,6.461470,6.569797,6.574199,6.486055,6.524562,6.609733,6.496900,...,6.546161,6.598870,6.594399,6.642574,6.570402,6.653920,6.601662,6.522618,6.550283,6.511778
9,ILMN_1668111,6.487908,6.451093,6.333161,6.313699,6.391719,6.430305,6.472588,6.555802,6.589110,...,6.529054,6.600233,6.470886,6.670124,6.655860,6.596334,6.409157,6.633256,6.667974,6.515780

In [ ]:
## Transpose the dataframe to get genes as columns and patients as rows
# row_filt2.transpose().to_csv('../data/GSE252168/row_norm_filt_v1.tsv', sep='\t')

In [107]:
# Re-upload the raw, normalized and filtered dataset to set column names correctly after transposition
row_final = pd.read_csv("../data/GSE252168/row_norm_filt_v1.tsv", sep="\t", header=1)
print(row_final.shape)
row_final.tail()

(303, 14045)

,ID_REF,ILMN_1762337,ILMN_1736007,ILMN_2383229,ILMN_1814316,ILMN_1668111,ILMN_1755321,ILMN_1698554,ILMN_1760414,ILMN_2061446,...,ILMN_1779783,ILMN_1685547,ILMN_2348512,ILMN_1743643,ILMN_1656676,ILMN_2371169,ILMN_1701875,ILMN_1786396,ILMN_1653618,ILMN_2137536
298,401_00284,6.595165,6.527477,6.644783,6.653920,6.596334,6.526061,6.592832,6.612689,6.769094,...,6.607670,6.568994,6.847434,7.091036,8.325324,9.047653,10.208228,7.991728,7.021209,6.844258
299,401_00293,6.567500,6.547211,6.790839,6.601662,6.409157,6.428100,6.525747,6.629240,7.459364,...,6.516997,6.557284,6.995918,7.709201,8.887472,9.879100,10.858933,8.326910,7.113353,6.608781
300,401_00302_mPT,6.603265,6.563996,6.644506,6.522618,6.633256,6.429833,6.610170,6.691532,7.322032,...,6.691532,6.547611,6.648252,7.506429,8.647909,10.601335,11.118321,8.050083,6.926629,6.718492
301,401_00304_mPT,6.594202,6.512566,6.550283,6.550283,6.667974,6.539723,6.630901,6.502081,7.704618,...,6.604225,6.551946,6.860182,7.467465,8.158668,10.424638,11.098932,8.018739,7.028455,6.590514
302,401_00309,6.484851,6.666084,6.633126,6.511778,6.515780,6.540613,6.686271,6.629574,7.249360,...,6.649627,6.644419,6.842600,7.348285,8.695352,9.789264,10.740029,8.074614,7.170778,6.845764

In [108]:
# Replace "401_" with "NLCB_" to match other mappings
row_final["ID_REF"] = row_final["ID_REF"].apply(lambda x: x.replace("401_", "NLCB_"))

In [109]:
# Verify the replace in the dataframe
row_final.tail()

,ID_REF,ILMN_1762337,ILMN_1736007,ILMN_2383229,ILMN_1814316,ILMN_1668111,ILMN_1755321,ILMN_1698554,ILMN_1760414,ILMN_2061446,...,ILMN_1779783,ILMN_1685547,ILMN_2348512,ILMN_1743643,ILMN_1656676,ILMN_2371169,ILMN_1701875,ILMN_1786396,ILMN_1653618,ILMN_2137536
298,NLCB_00284,6.595165,6.527477,6.644783,6.653920,6.596334,6.526061,6.592832,6.612689,6.769094,...,6.607670,6.568994,6.847434,7.091036,8.325324,9.047653,10.208228,7.991728,7.021209,6.844258
299,NLCB_00293,6.567500,6.547211,6.790839,6.601662,6.409157,6.428100,6.525747,6.629240,7.459364,...,6.516997,6.557284,6.995918,7.709201,8.887472,9.879100,10.858933,8.326910,7.113353,6.608781
300,NLCB_00302_mPT,6.603265,6.563996,6.644506,6.522618,6.633256,6.429833,6.610170,6.691532,7.322032,...,6.691532,6.547611,6.648252,7.506429,8.647909,10.601335,11.118321,8.050083,6.926629,6.718492
301,NLCB_00304_mPT,6.594202,6.512566,6.550283,6.550283,6.667974,6.539723,6.630901,6.502081,7.704618,...,6.604225,6.551946,6.860182,7.467465,8.158668,10.424638,11.098932,8.018739,7.028455,6.590514
302,NLCB_00309,6.484851,6.666084,6.633126,6.511778,6.515780,6.540613,6.686271,6.629574,7.249360,...,6.649627,6.644419,6.842600,7.348285,8.695352,9.789264,10.740029,8.074614,7.170778,6.845764

In [111]:
# Finally order the dataframe to have same order with ids to patients status mapping later
row_final.sort_values("ID_REF", inplace = True)

In [113]:
print(row_final.shape)
row_final.tail()

(303, 14045)

,ID_REF,ILMN_1762337,ILMN_1736007,ILMN_2383229,ILMN_1814316,ILMN_1668111,ILMN_1755321,ILMN_1698554,ILMN_1760414,ILMN_2061446,...,ILMN_1779783,ILMN_1685547,ILMN_2348512,ILMN_1743643,ILMN_1656676,ILMN_2371169,ILMN_1701875,ILMN_1786396,ILMN_1653618,ILMN_2137536
175,NOWAC_5B,6.531632,6.499108,6.365981,6.450881,6.524840,6.549987,6.641334,6.531632,6.967227,...,6.536997,6.658629,6.711463,7.019359,8.900990,9.098768,10.474797,7.862920,7.198008,6.903458
176,NOWAC_7A,6.567050,6.591830,6.715754,6.655813,6.612536,6.454206,6.593411,6.552935,7.281150,...,6.670899,6.546608,6.715754,7.063923,8.641807,9.772629,10.945319,8.039093,7.253221,7.003934
177,NOWAC_7B,6.656754,6.987219,6.523385,6.701857,6.605290,6.538122,6.373929,6.686852,6.715530,...,6.954275,6.525012,6.710381,7.261730,9.365524,9.889303,10.515257,7.982219,6.802289,6.895746
178,NOWAC_9A,6.671315,6.436563,6.657005,6.530105,6.590504,6.521079,6.652935,6.432178,6.968300,...,6.499465,6.513011,6.802019,7.031210,9.132702,9.371050,10.484725,7.669684,7.242400,6.865260
179,NOWAC_9B,6.605605,6.474139,6.497111,6.603995,6.493992,6.490900,6.644487,6.561022,7.036561,...,6.579945,6.607189,6.681755,6.955799,8.699763,9.335078,10.493529,7.918838,7.262251,6.872069

In [ ]:
# # Save the final version of raw, normalized and filtered expression matrix
# row_final.to_csv('../data/GSE252168/row_filtered.tsv', sep="\t", index = False)

## Part 2: Map patient IDs to health conditions
- Metadata of our study can be found in the data folder as [metadata_table](../data/GSE252168/metadata_table.html). 
- We will use this metadata to create a mapping between patient IDs and their corresponding health conditions (Control vs Lung Cancer) for later use in IG calculation.
- Mapping itself is stored as [id_to_health_status](../data/GSE252168/id_to_health_status.tsv) in the data folder.

In [ ]:
# Check the metadata before filtering for patient IDs and health status
metadata = pd.read_html("../data/GSE252168/metadata_table.html")
metadata1 = metadata[0]
print(metadata1.shape)
metadata1.head()

(303, 22)

,Group,Accession,Title,Source name,Tissue,Concentration_rna,Rin_rna,Ratio_260_280_rna,Biobank,Gender,...,Smoking_status,Crp,Tumor_size,Stage,Histology,Time_to_death,Block,Outlier,Dataset,Status
0,-,GSM7995432,blood_HUNT_1,peripheral whole blood,peripheral whole blood,172.9,7.2,2.1,HUNT,Male,...,smoker,22.2,NaN,NaN,NaN,NaN,block_117,False,NH_M_53,control
1,-,GSM7995433,blood_HUNT_10,peripheral whole blood,peripheral whole blood,84.1,7.6,2.1,HUNT,Male,...,smoker,0.3,NaN,NaN,NaN,NaN,block_18,False,NH_M_53,control
2,-,GSM7995434,blood_HUNT_100,peripheral whole blood,peripheral whole blood,103.3,4.7,2.1,HUNT,Male,...,smoker,0.6,NaN,NaN,NaN,NaN,block_102,False,NH_M_53,control
3,-,GSM7995435,blood_HUNT_101,peripheral whole blood,peripheral whole blood,71.9,4.4,2.1,HUNT,Male,...,smoker,1.2,NaN,NaN,NaN,NaN,block_100,False,NH_M_53,control
4,-,GSM7995436,blood_HUNT_102,peripheral whole blood,peripheral whole blood,59.6,6.9,2.2,HUNT,Male,...,smoker,0.6,NaN,NaN,NaN,NaN,block_114,False,NH_M_53,control

In [130]:
# Get corresponding health condition for each patient in a different dataframe
id_to_cond = metadata1.filter(["Title", "Status"], axis="columns")
print(id_to_cond.shape)
id_to_cond.tail()

(303, 2)

                    Title Status
298      blood_NLCB_00284   case
299      blood_NLCB_00293   case
300  blood_NLCB_00302_mPT   case
301  blood_NLCB_00304_mPT   case
302      blood_NLCB_00309   case

In [131]:
# Remove the "blood" phrase since our expression map IDs do not contain that phrase
id_to_cond["Title"] = id_to_cond["Title"].apply(lambda x: x.replace("blood_", ""))
id_to_cond.head()

      Title   Status
0    HUNT_1  control
1   HUNT_10  control
2  HUNT_100  control
3  HUNT_101  control
4  HUNT_102  control

In [132]:
# Replace "case" status via "lung cancer"
id_to_cond.replace("case","lung cancer",inplace=True)
id_to_cond.tail()

              Title       Status
298      NLCB_00284  lung cancer
299      NLCB_00293  lung cancer
300  NLCB_00302_mPT  lung cancer
301  NLCB_00304_mPT  lung cancer
302      NLCB_00309  lung cancer

In [133]:
# Check how many controls and lung cancer patients there to verify 
id_to_cond["Status"].value_counts()

Status
control        180
lung cancer    123
Name: count, dtype: int64

In [134]:
# Sort the ID column to get same order with expression matrix
id_to_cond.sort_values("Title", inplace= True)

In [ ]:
# Get id order from the expression matrix
patient_ids = pd.read_csv("../data/GSE252168/row_filtered.tsv", sep="\t", usecols= ["ID_REF"])

In [136]:
# Check whether the order of the samples match 
match_order = [i for i, j in zip(id_to_cond["Title"], patient_ids["ID_REF"]) if i == j]
len(match_order)

303

In [ ]:
# # Save the patient IDs and their corresponding health conditions to a tsv 
# id_to_cond.to_csv("../data/GSE252168/id_to_health_status.tsv", sep="\t",index=False)