# Phase III: modification of PPI network with gene expression correlations

## Part 1: Create Mapping Dictionary from Ensembl IDs of proteins to HGNC symbols

In [1]:
import networkx as nx
import pandas as pd

In [ ]:
# Upload information table from STRING to map protein IDs to gene symbols
info_df = pd.read_csv("../data/STRING/9606.protein.info.v12.0.txt", sep="\t", usecols=[0,1])
print(info_df.shape)
info_df.head()

(19699, 2)

     #string_protein_id preferred_name
0  9606.ENSP00000000233           ARF5
1  9606.ENSP00000000412           M6PR
2  9606.ENSP00000001008          FKBP4
3  9606.ENSP00000001146        CYP26B1
4  9606.ENSP00000002125        NDUFAF7

In [ ]:
# Check for empty rows
info_df.isna().value_counts()

#string_protein_id  preferred_name
False               False             19699
Name: count, dtype: int64

In [ ]:
# Check for duplicate HGNC symbols
info_df["preferred_name"].duplicated().value_counts()

preferred_name
False    19699
Name: count, dtype: int64

In [5]:
# Create mapping dict 
protein_id_to_symbol = dict(zip(info_df["#string_protein_id"],info_df["preferred_name"]))
print(protein_id_to_symbol)

{'9606.ENSP00000000233': 'ARF5', '9606.ENSP00000000412': 'M6PR', '9606.ENSP00000001008': 'FKBP4', '9606.ENSP00000001146': 'CYP26B1', '9606.ENSP00000002125': 'NDUFAF7', '9606.ENSP00000002165': 'FUCA2', '9606.ENSP00000002596': 'HS3ST1', '9606.ENSP00000002829': 'SEMA3F', '9606.ENSP00000003084': 'CFTR', '9606.ENSP00000003100': 'CYP51A1', '9606.ENSP00000003302': 'USP28', '9606.ENSP00000004531': 'SLC7A2', '9606.ENSP00000004982': 'HSPB6', '9606.ENSP00000005178': 'PDK4', '9606.ENSP00000005226': 'USH1C', '9606.ENSP00000005257': 'RALA', '9606.ENSP00000005260': 'BAIAP2L1', '9606.ENSP00000005284': 'CACNG3', '9606.ENSP00000005286': 'TMEM132A', '9606.ENSP00000005340': 'DVL2', '9606.ENSP00000005386': 'RPAP3', '9606.ENSP00000005587': 'SKAP2', '9606.ENSP00000005995': 'PRSS21', '9606.ENSP00000006015': 'HOXA11', '9606.ENSP00000006053': 'CX3CL1', '9606.ENSP00000006275': 'TRAPPC6A', '9606.ENSP00000006526': 'WDR54', '9606.ENSP00000006658': 'SPATA20', '9606.ENSP00000006724': 'CEACAM7', '9606.ENSP00000006777': 'RHBDD2', '9606.ENSP00000007390': 'TSR3', '9606.ENSP00000007414': 'OSBPL7', '9606.ENSP00000007699': 'YBX2', '9606.ENSP00000007735': 'KRT33A', '9606.ENSP00000008391': 'TFAP2D', '9606.ENSP00000008527': 'CRY1', '9606.ENSP00000008938': 'PGLYRP1', '9606.ENSP00000009041': 'STARD3NL', '9606.ENSP00000009105': 'CAMK1G', '9606.ENSP00000009530': 'CD74', '9606.ENSP00000010299': 'FAM76A', '9606.ENSP00000011292': 'CPA1', '9606.ENSP00000011473': 'SYPL1', '9606.ENSP00000011619': 'RANBP9', '9606.ENSP00000011653': 'CD4', '9606.ENSP00000011898': 'TSPAN9', '9606.ENSP00000012049': 'QPCTL', '9606.ENSP00000012443': 'PPP5C', '9606.ENSP00000013070': 'UBR7', '9606.ENSP00000013125': 'MAP4K5', '9606.ENSP00000013222': 'INMT', '9606.ENSP00000013807': 'ERCC1', '9606.ENSP00000014914': 'GPRC5A', '9606.ENSP00000014930': 'HEBP1', '9606.ENSP00000016171': 'COX15', '9606.ENSP00000016913': 'MS4A12', '9606.ENSP00000016946': 'RGPD5', '9606.ENSP00000017003': 'XYLT2', '9606.ENSP00000019103': 'SCTR', '9606.ENSP00000020926': 'SYT13', '9606.ENSP00000020945': 'SNAI2', '9606.ENSP00000023064': 'SLC7A9', '9606.ENSP00000023939': 'RTF2', '9606.ENSP00000025008': 'RB1CC1', '9606.ENSP00000025301': 'AKAP11', '9606.ENSP00000026218': 'PIGQ', '9606.ENSP00000027335': 'CDH17', '9606.ENSP00000029410': 'B4GALT7', '9606.ENSP00000033079': 'FAM13B', '9606.ENSP00000035307': 'CHPF2', '9606.ENSP00000037243': 'GABARAPL2', '9606.ENSP00000037502': 'MYOC', '9606.ENSP00000039007': 'OTC', '9606.ENSP00000039989': 'TTC17', '9606.ENSP00000040584': 'HOXC8', '9606.ENSP00000040663': 'MRI1', '9606.ENSP00000040738': 'BOD1L1', '9606.ENSP00000040877': 'TARBP1', '9606.ENSP00000043402': 'RTN4R', '9606.ENSP00000044462': 'PSMA4', '9606.ENSP00000045083': 'RIPOR3', '9606.ENSP00000046087': 'ZPBP', '9606.ENSP00000046794': 'LCP2', '9606.ENSP00000052754': 'DCN', '9606.ENSP00000053243': 'TNFRSF17', '9606.ENSP00000053468': 'MRPS10', '9606.ENSP00000053469': 'GUCA1A', '9606.ENSP00000053867': 'GRN', '9606.ENSP00000054650': 'THAP3', '9606.ENSP00000054666': 'VAMP3', '9606.ENSP00000054668': 'UTS2', '9606.ENSP00000054950': 'RCN1', '9606.ENSP00000055077': 'RFC2', '9606.ENSP00000055335': 'PPP1R3F', '9606.ENSP00000055682': 'NEXMIF', '9606.ENSP00000056217': 'ARHGEF5', '9606.ENSP00000056233': 'NFE2L3', '9606.ENSP00000061240': 'TLL1', '9606.ENSP00000064571': 'CBLN4', '9606.ENSP00000064724': 'CLDN11', '9606.ENSP00000064778': 'FAM168A', '9606.ENSP00000064780': 'RELT', '9606.ENSP00000070846': 'PKP2', '9606.ENSP00000072644': 'YIPF1', '9606.ENSP00000072869': 'ADCK2', '9606.ENSP00000074304': 'INPP4A', '9606.ENSP00000075120': 'SLC2A3', '9606.ENSP00000075503': 'STYK1', '9606.ENSP00000078429': 'GNA11', '9606.ENSP00000078445': 'CREB3L3', '9606.ENSP00000080059': 'HDAC7', '9606.ENSP00000081029': 'MRPS35', '9606.ENSP00000083182': 'APPBP2', '9606.ENSP00000084798': 'CA11', '9606.ENSP00000085068': 'ISOC2', '9606.ENSP00000085219': 'CD22', '9606.ENSP00000086933': 'GSC2', '9606.ENSP00000155093': 'ZFY', '9606.ENSP00000155840': 'KCNQ1', '9606.ENSP00000155858': 'TRPM5', '9606.ENSP00000155926': 'TRIB2', '9606.ENSP00000156084': 'OTUD5', '9606.ENSP00000156109': 'GPKOW', '9606.ENSP00000156471': 'AQR', '9606.ENSP00000156626': 'ST6GALNAC1', '9606.ENSP00000157600': 'LMCD1', '9606.ENSP00000157812': 'PSMC4', '9606.ENSP00000158009': 'FNDC8', '9606.ENSP00000158762': 'ACAP1', '9606.ENSP00000158771': 'DERL2', '9606.ENSP00000159060': 'NOX3', '9606.ENSP00000159087': 'ANO8', '9606.ENSP00000159111': 'KDM4B', '9606.ENSP00000160262': 'ICAM3', '9606.ENSP00000160373': 'CTTNBP2', '9606.ENSP00000160382': 'ACTL6B', '9606.ENSP00000160827': 'KIF22', '9606.ENSP00000161006': 'PRSS22', '9606.ENSP00000161559': 'CEACAM1', '9606.ENSP00000161863': 'YTHDC2', '9606.ENSP00000162044': 'TMEM161A', '9606.ENSP00000162391': 'FOXJ2', '9606.ENSP00000162749': 'TNFRSF1A', '9606.ENSP00000163416': 'GOLGA5', '9606.ENSP00000164024': 'CELSR3', '9606.ENSP00000164133': 'PPP2R5B', '9606.ENSP00000164139': 'PYGM', '9606.ENSP00000164227': 'BCL3', '9606.ENSP00000164305': 'PIGB', '9606.ENSP00000165524': 'PRLH', '9606.ENSP00000166139': 'FSTL3', '9606.ENSP00000166244': 'EPHA8', '9606.ENSP00000166345': 'TRIP13', '9606.ENSP00000167106': 'VASH1', '9606.ENSP00000167586': 'KRT14', '9606.ENSP00000167588': 'KRT20', '9606.ENSP00000168148': 'SPP2', '9606.ENSP00000168216': 'HSD17B10', '9606.ENSP00000168712': 'FGF4', '9606.ENSP00000169298': 'ST6GAL1', '9606.ENSP00000169551': 'TIMM21', '9606.ENSP00000170150': 'BPIFB2', '9606.ENSP00000170168': 'REXO1', '9606.ENSP00000170447': 'MKRN2', '9606.ENSP00000170564': 'GPATCH1', '9606.ENSP00000171757': 'P2RY10', '9606.ENSP00000171887': 'TNS1', '9606.ENSP00000172229': 'NGFR', '9606.ENSP00000173229': 'NTN1', '9606.ENSP00000173527': 'ISOC1', '9606.ENSP00000173898': 'TRO', '9606.ENSP00000174618': 'MNT', '9606.ENSP00000175091': 'LAPTM4A', '9606.ENSP00000175238': 'ADAM7', '9606.ENSP00000175756': 'PTPN18', '9606.ENSP00000176183': 'DRD4', '9606.ENSP00000176195': 'SCT', '9606.ENSP00000176763': 'STK10', '9606.ENSP00000177694': 'TBX21', '9606.ENSP00000177742': 'MRPS34', '9606.ENSP00000178638': 'CA12', '9606.ENSP00000178640': 'MAP2K5', '9606.ENSP00000179259': 'TIGAR', '9606.ENSP00000180166': 'FGF20', '9606.ENSP00000180173': 'MTMR7', '9606.ENSP00000181383': 'CPB2', '9606.ENSP00000181796': 'FAM107B', '9606.ENSP00000181839': 'CDK13', '9606.ENSP00000182290': 'TSPAN32', '9606.ENSP00000182527': 'TRAM2', '9606.ENSP00000184183': 'ROPN1', '9606.ENSP00000184266': 'NDUFB4', '9606.ENSP00000184956': 'HEATR6', '9606.ENSP00000185150': 'ERLEC1', '9606.ENSP00000185206': 'CLIC5', '9606.ENSP00000186436': 'TMEM131', '9606.ENSP00000187762': 'TMEM38A', '9606.ENSP00000188312': 'ACTR6', '9606.ENSP00000188790': 'FAP', '9606.ENSP00000190165': 'DMRT3', '9606.ENSP00000192314': 'GAL3ST2', '9606.ENSP00000192788': 'UHRF1BP1', '9606.ENSP00000193322': 'OSTM1', '9606.ENSP00000193391': 'IMPG2', '9606.ENSP00000194130': 'SLC13A1', '9606.ENSP00000194152': 'PCDHB4', '9606.ENSP00000194155': 'PCDHB2', '9606.ENSP00000194214': 'HSPB11', '9606.ENSP00000194530': 'STRADB', '9606.ENSP00000196061': 'PLOD1', '9606.ENSP00000196371': 'OXCT1', '9606.ENSP00000196489': 'ZNF416', '9606.ENSP00000197268': 'FAM234B', '9606.ENSP00000198536': 'PILRA', '9606.ENSP00000198767': 'RRN3', '9606.ENSP00000198801': 'MOGAT2', '9606.ENSP00000199280': 'AQP2', '9606.ENSP00000199320': 'DIMT1', '9606.ENSP00000199389': 'EIF2AK1', '9606.ENSP00000199447': 'NME8', '9606.ENSP00000199448': 'EPDR1', '9606.ENSP00000199708': 'HBQ1', '9606.ENSP00000199764': 'CEACAM6', '9606.ENSP00000199814': 'RBM22', '9606.ENSP00000199936': 'HSD17B2', '9606.ENSP00000200135': 'ZW10', '9606.ENSP00000200181': 'ITGB4', '9606.ENSP00000200453': 'PPP1R15A', '9606.ENSP00000200457': 'TRIP6', '9606.ENSP00000200557': 'ADAM11', '9606.ENSP00000200652': 'SLC22A4', '9606.ENSP00000200676': 'CETP', '9606.ENSP00000200691': 'MT3', '9606.ENSP00000201031': 'TFAP2C', '9606.ENSP00000201586': 'SULT2B1', '9606.ENSP00000201647': 'EPS8L1', '9606.ENSP00000201979': 'REM1', '9606.ENSP00000202017': 'PDRG1', '9606.ENSP00000202556': 'PPP1R13B', '9606.ENSP00000202625': 'TGM6', '9606.ENSP00000202677': 'RALGAPA2', '9606.ENSP00000202816': 'ESF1', '9606.ENSP00000202967': 'SIRT4', '9606.ENSP00000203001': 'TRMT6', '9606.ENSP00000203407': 'UQCRC1', '9606.ENSP00000203556': 'GMIP', '9606.ENSP00000203629': 'LAG3', '9606.ENSP00000203630': 'MLF2', '9606.ENSP00000203664': 'OTUB2', '9606.ENSP00000204517': 'TFAP4', '9606.ENSP00000204549': 'PDCD7', '9606.ENSP00000204566': 'SPG21', '9606.ENSP00000204604': 'CHRD', '9606.ENSP00000204679': 'GNPTG', '9606.ENSP00000204726': 'GOLGA3', '9606.ENSP00000204961': 'EFNB1', '9606.ENSP00000205061': 'GLG1', '9606.ENSP00000205143': 'DLL3', '9606.ENSP00000205194': 'NAT14', '9606.ENSP00000205214': 'AASDH', '9606.ENSP00000205402': 'DLD', '9606.ENSP00000205557': 'ABCC6', '9606.ENSP00000205636': 'CMTM6', '9606.ENSP00000205948': 'APOH', '9606.ENSP00000206020': 'SPAG7', '9606.ENSP00000206262': 'RGS17', '9606.ENSP00000206423': 'CCDC80', '9606.ENSP00000206474': 'HAUS4', '9606.ENSP00000206513': 'CEBPE', '9606.ENSP00000206542': 'OSGEP', '9606.ENSP00000206595': 'G2E3', '9606.ENSP00000206765': 'TGM1', '9606.ENSP00000207457': 'TEKT2', '9606.ENSP00000207549': 'UNC13D', '9606.ENSP00000207870': 'XYLB', '9606.ENSP00000209668': 'ADH1A', '9606.ENSP00000209718': 'KRT23', '9606.ENSP00000209728': 'CDC6', '9606.ENSP00000209873': 'AAAS', '9606.ENSP00000209875': 'CBX5', '9606.ENSP00000209884': 'KLHL20', '9606.ENSP00000209929': 'FMO2', '9606.ENSP00000210060': 'DHPS', '9606.ENSP00000210187': 'RAB26', '9606.ENSP00000210313': 'PSMD5', '9606.ENSP00000210444': 'NANS', '9606.ENSP00000210633': 'SEMA4G', '9606.ENSP00000211076': 'TPSD1', '9606.ENSP00000211122': 'GSTA3', '9606.ENSP00000211287': 'MAPK13', '9606.ENSP00000211314': 'TMEM14A', '9606.ENSP00000211413': 'PRRT1', '9606.ENSP00000211936': 'ZNF184', '9606.ENSP00000211998': 'VCL', '9606.ENSP00000212015': 'SIRT1', '9606.ENSP00000212355': 'TGFBR3', '9606.ENSP00000214869': 'TMED1', '9606.ENSP00000215057': 'MZF1', '9606.ENSP00000215061': 'OCEL1', '9606.ENSP00000215071': 'PSMD8', '9606.ENSP00000215095': 'STX1B', '9606.ENSP00000215368': 'EFNA2', '9606.ENSP00000215375': 'ATP5F1D', '9606.ENSP00000215530': 'FGF22', '9606.ENSP00000215531': 'SMIM24', '9606.ENSP00000215565': 'NDUFB7', '9606.ENSP00000215567': 'TECR', '9606.ENSP00000215570': 'TIMM13', '9606.ENSP00000215574': 'CDC34', '9606.ENSP00000215582': 'MISP', '9606.ENSP00000215631': 'GADD45B', '9606.ENSP00000215637': 'MADCAM1', '9606.ENSP00000215659': 'MAPK12', '9606.ENSP00000215727': 'SERPIND1', '9606.ENSP00000215730': 'SNAP29', '9606.ENSP00000215742': 'THAP7', '9606.ENSP00000215743': 'MMP11', '9606.ENSP00000215754': 'MIF', '9606.ENSP00000215770': 'DDTL', '9606.ENSP00000215781': 'OSM', '9606.ENSP00000215793': 'SF3A1', '9606.ENSP00000215794': 'USP18', '9606.ENSP00000215812': 'SEC14L3', '9606.ENSP00000215829': 'SNRPD3', '9606.ENSP00000215832': 'MAPK1', '9606.ENSP00000215838': 'TCN2', '9606.ENSP00000215855': 'CRYBB3', '9606.ENSP00000215882': 'SLC25A1', '9606.ENSP00000215885': 'PLA2G3', '9606.ENSP00000215886': 'LGALS2', '9606.ENSP00000215904': 'PDXP', '9606.ENSP00000215906': 'ASPHD2', '9606.ENSP00000215909': 'LGALS1', '9606.ENSP00000215912': 'PIK3IP1', '9606.ENSP00000215917': 'SRRD', '9606.ENSP00000215941': 'ANKRD54', '9606.ENSP00000215957': 'MICALL1', '9606.ENSP00000215980': 'CENPM', '9606.ENSP00000216024': 'DMC1', '9606.ENSP00000216027': 'HSCB', '9606.ENSP00000216034': 'TOMM22', '9606.ENSP00000216036': 'RSPH14', '9606.ENSP00000216037': 'XBP1', '9606.ENSP00000216038': 'RTCB', '9606.ENSP00000216039': 'JOSD1', '9606.ENSP00000216044': 'GTPBP1', '9606.ENSP00000216068': 'DNAL4', '9606.ENSP00000216071': 'C22orf31', '9606.ENSP00000216075': 'MIOX', '9606.ENSP00000216085': 'RHBDD3', '9606.ENSP00000216099': 'APOBEC3D', '9606.ENSP00000216101': 'RASL10A', '9606.ENSP00000216106': 'HMGXB4', '9606.ENSP00000216115': 'BIK', '9606.ENSP00000216117': 'HMOX1', '9606.ENSP00000216121': 'NIPSNAP1', '9606.ENSP00000216122': 'MCM5', '9606.ENSP00000216124': 'ARSA', '9606.ENSP00000216127': 'RASD2', '9606.ENSP00000216129': 'TTLL12', '9606.ENSP00000216133': 'CBX7', '9606.ENSP00000216139': 'ACR', '9606.ENSP00000216144': 'CABP7', '9606.ENSP00000216160': 'TAB1', '9606.ENSP00000216177': 'PNPLA5', '9606.ENSP00000216180': 'PNPLA3', '9606.ENSP00000216181': 'MYH9', '9606.ENSP00000216185': 'TXN2', '9606.ENSP00000216190': 'EIF3D', '9606.ENSP00000216200': 'PVALB', '9606.ENSP00000216211': 'UPK3A', '9606.ENSP00000216214': 'FAM118A', '9606.ENSP00000216218': 'ST13', '9606.ENSP00000216223': 'IL2RB', '9606.ENSP00000216225': 'RBX1', '9606.ENSP00000216237': 'L3MBTL2', '9606.ENSP00000216241': 'CHADL', '9606.ENSP00000216252': 'PHF5A', '9606.ENSP00000216254': 'ACO2', '9606.ENSP00000216259': 'PMM1', '9606.ENSP00000216264': 'CERK', '9606.ENSP00000216268': 'ZBED4', '9606.ENSP00000216271': 'HDAC10', '9606.ENSP00000216274': 'RIPK3', '9606.ENSP00000216277': 'PAPOLA', '9606.ENSP00000216286': 'NID2', '9606.ENSP00000216294': 'SNAPC1', '9606.ENSP00000216297': 'SUPT16H', '9606.ENSP00000216330': 'FKBP3', '9606.ENSP00000216336': 'CTSG', '9606.ENSP00000216338': 'GZMH', '9606.ENSP00000216341': 'GZMB', '9606.ENSP00000216361': 'COCH', '9606.ENSP00000216366': 'AP4S1', '9606.ENSP00000216367': 'POLE2', '9606.ENSP00000216373': 'SOS2', '9606.ENSP00000216392': 'PYGL', '9606.ENSP00000216410': 'GNPNAT1', '9606.ENSP00000216416': 'CNIH1', '9606.ENSP00000216420': 'CGRRF1', '9606.ENSP00000216442': 'ATP6V1D', '9606.ENSP00000216446': 'PLEK2', '9606.ENSP00000216452': 'PIGH', '9606.ENSP00000216455': 'PSMA3', '9606.ENSP00000216468': 'TMED8', '9606.ENSP00000216471': 'SAMD15', '9606.ENSP00000216479': 'AHSA1', '9606.ENSP00000216484': 'SPTLC2', '9606.ENSP00000216487': 'RIN3', '9606.ENSP00000216489': 'ALKBH1', '9606.ENSP00000216492': 'CHGA', '9606.ENSP00000216500': 'DHRS7', '9606.ENSP00000216513': 'SIX4', '9606.ENSP00000216540': 'SLC10A1', '9606.ENSP00000216554': 'EIF5', '9606.ENSP00000216602': 'ZFYVE21', '9606.ENSP00000216629': 'BDKRB1', '9606.ENSP00000216639': 'VRK1', '9606.ENSP00000216714': 'APEX1', '9606.ENSP00000216727': 'PABPN1', '9606.ENSP00000216733': 'EFS', '9606.ENSP00000216756': 'CINP', '9606.ENSP00000216780': 'PCK2', '9606.ENSP00000216797': 'NFKBIA', '9606.ENSP00000216802': 'PSME2', '9606.ENSP00000216807': 'BRMS1L', '9606.ENSP00000216832': 'PNN', '9606.ENSP00000216862': 'CYP24A1', '9606.ENSP00000216911': 'AURKA', '9606.ENSP00000216923': 'ZFP64', '9606.ENSP00000216962': 'PYGB', '9606.ENSP00000216968': 'PROCR', '9606.ENSP00000217026': 'MYBL2', '9606.ENSP00000217043': 'R3HDML', '9606.ENSP00000217086': 'SALL4', '9606.ENSP00000217109': 'CSTF1', '9606.ENSP00000217121': 'TPD52L2', '9606.ENSP00000217131': 'CTSZ', '9606.ENSP00000217133': 'TUBB1', '9606.ENSP00000217159': 'SLCO4A1', '9606.ENSP00000217169': 'BIRC7', '9606.ENSP00000217173': 'UBOX5', '9606.ENSP00000217182': 'EEF1A2', '9606.ENSP00000217188': 'SRMS', '9606.ENSP00000217195': 'C20orf27', '9606.ENSP00000217244': 'CSNK2A1', '9606.ENSP00000217246': 'MACROD2', '9606.ENSP00000217260': 'RSPO4', '9606.ENSP00000217270': 'PROKR2', '9606.ENSP00000217289': 'FERMT1', '9606.ENSP00000217320': 'TLDC2', '9606.ENSP00000217372': 'CDK5RAP1', '9606.ENSP00000217381': 'SNTA1', '9606.ENSP00000217386': 'OXT', '9606.ENSP00000217402': 'CHMP4B', '9606.ENSP00000217407': 'LBP', '9606.ENSP00000217420': 'SLC32A1', '9606.ENSP00000217423': 'CST4', '9606.ENSP00000217426': 'AHCY', '9606.ENSP00000217428': 'SPINT3', '9606.ENSP00000217446': 'PIGU', '9606.ENSP00000217455': 'ACOT8', '9606.ENSP00000217456': 'APMAP', '9606.ENSP00000217515': 'TXNL1', '9606.ENSP00000217740': 'RNF125', '9606.ENSP00000217901': 'IDH3G', '9606.ENSP00000217909': 'SLC25A43', '9606.ENSP00000217939': 'MXRA5', '9606.ENSP00000217958': 'PSMD10', '9606.ENSP00000217961': 'STS', '9606.ENSP00000217971': 'PGRMC1', '9606.ENSP00000217999': 'RHOXF1', '9606.ENSP00000218004': 'NXT2', '9606.ENSP00000218006': 'GUCY2F', '9606.ENSP00000218008': 'ATP1B4', '9606.ENSP00000218068': 'PAGE4', '9606.ENSP00000218075': 'GLRA2', '9606.ENSP00000218089': 'STAG2', '9606.ENSP00000218099': 'F9', '9606.ENSP00000218104': 'ABCD1', '9606.ENSP00000218176': 'KCND1', '9606.ENSP00000218230': 'PCSK1N', '9606.ENSP00000218249': 'RAB40AL', '9606.ENSP00000218316': 'GPR50', '9606.ENSP00000218340': 'RP2', '9606.ENSP00000218348': 'USP11', '9606.ENSP00000218388': 'TIMP1', '9606.ENSP00000218436': 'ITIH6', '9606.ENSP00000218516': 'GLA', '9606.ENSP00000218548': 'ATP12A', '9606.ENSP00000218721': 'MLNR', '9606.ENSP00000218758': 'ACP5', '9606.ENSP00000218867': 'SGCG', '9606.ENSP00000219022': 'OLFM4', '9606.ENSP00000219066': 'NTHL1', '9606.ENSP00000219069': 'ZNF263', '9606.ENSP00000219070': 'MMP2', '9606.ENSP00000219097': 'ORC6', '9606.ENSP00000219139': 'C16orf70', '9606.ENSP00000219150': 'CORO1A', '9606.ENSP00000219162': 'MT4', '9606.ENSP00000219169': 'NUTF2', '9606.ENSP00000219197': 'CBLN1', '9606.ENSP00000219204': 'ARL2BP', '9606.ENSP00000219207': 'PLLP', '9606.ENSP00000219235': 'CCL22', '9606.ENSP00000219240': 'DHODH', '9606.ENSP00000219244': 'CCL17', '9606.ENSP00000219252': 'POLR2C', '9606.ENSP00000219255': 'PARD6A', '9606.ENSP00000219271': 'MMP15', '9606.ENSP00000219281': 'USB1', '9606.ENSP00000219299': 'CCDC113', '9606.ENSP00000219301': 'PRSS54', '9606.ENSP00000219302': 'NME3', '9606.ENSP00000219313': 'PSMD7', '9606.ENSP00000219315': 'SETD6', '9606.ENSP00000219334': 'SMPD3', '9606.ENSP00000219345': 'PLA2G15', '9606.ENSP00000219368': 'FA2H', '9606.ENSP00000219400': 'CMC2', '9606.ENSP00000219406': 'PDIA2', '9606.ENSP00000219409': 'ARHGDIG', '9606.ENSP00000219431': 'MPG', '9606.ENSP00000219439': 'HSDL1', '9606.ENSP00000219476': 'TSC2', '9606.ENSP00000219478': 'ZNF500', '9606.ENSP00000219479': 'NME4', '9606.ENSP00000219481': 'DECR2', '9606.ENSP00000219548': 'STUB1', '9606.ENSP00000219551': 'RHBDL1', '9606.ENSP00000219596': 'MEFV', '9606.ENSP00000219599': 'CRYM', '9606.ENSP00000219611': 'CAPN15', '9606.ENSP00000219660': 'AQP8', '9606.ENSP00000219689': 'USP31', '9606.ENSP00000219746': 'TOX3', '9606.ENSP00000219782': 'MAZ', '9606.ENSP00000219789': 'CDIPT', '9606.ENSP00000219833': 'SLC6A2', '9606.ENSP00000219837': 'KNOP1', '9606.ENSP00000219905': 'MGA', '9606.ENSP00000219919': 'AQP9', '9606.ENSP00000220003': 'CSK', '9606.ENSP00000220058': 'MTFMT', '9606.ENSP00000220062': 'RASL12', '9606.ENSP00000220166': 'CTSH', '9606.ENSP00000220325': 'EHD4', '9606.ENSP00000220420': 'TGM5', '9606.ENSP00000220429': 'GABPB1', '9606.ENSP00000220478': 'SCG3', '9606.ENSP00000220496': 'DNAJC17', '9606.ENSP00000220507': 'RHOV', '9606.ENSP00000220509': 'VPS18', '9606.ENSP00000220514': 'OIP5', '9606.ENSP00000220562': 'EXTL3', '9606.ENSP00000220592': 'AGO2', '9606.ENSP00000220597': 'PAG1', '9606.ENSP00000220616': 'TG', '9606.ENSP00000220659': 'BRF2', '9606.ENSP00000220669': 'ZFAND1', '9606.ENSP00000220676': 'RP1', '9606.ENSP00000220751': 'RIPK2', '9606.ENSP00000220763': 'CPQ', '9606.ENSP00000220764': 'DECR1', '9606.ENSP00000220772': 'SFRP1', '9606.ENSP00000220809': 'PLAT', '9606.ENSP00000220812': 'DKK4', '9606.ENSP00000220822': 'GDAP1', '9606.ENSP00000220849': 'EIF3E', '9606.ENSP00000220853': 'EMC2', '9606.ENSP00000220913': 'CHRAC1', '9606.ENSP00000220940': 'GML', '9606.ENSP00000220966': 'PYCR3', '9606.ENSP00000221086': 'MTMR9', '9606.ENSP00000221114': 'DCTN6', '9606.ENSP00000221130': 'GSR', '9606.ENSP00000221132': 'TNFRSF10A', '9606.ENSP00000221138': 'PPP2CB', '9606.ENSP00000221166': 'NEFM', '9606.ENSP00000221200': 'KCTD9', '9606.ENSP00000221233': 'EXOSC5', '9606.ENSP00000221265': 'PAF1', '9606.ENSP00000221307': 'CYP4F3', '9606.ENSP00000221315': 'ZNF432', '9606.ENSP00000221327': 'ZNF180', '9606.ENSP00000221399': 'TULP2', '9606.ENSP00000221403': 'DHDH', '9606.ENSP00000221418': 'ECH1', '9606.ENSP00000221419': 'HNRNPL', '9606.ENSP00000221444': 'KCNA7', '9606.ENSP00000221452': 'RELB', '9606.ENSP00000221455': 'CLASRP', '9606.ENSP00000221459': 'LIN7B', '9606.ENSP00000221462': 'PPP1R37', '9606.ENSP00000221476': 'CKM', '9606.ENSP00000221480': 'PEX11G', '9606.ENSP00000221485': 'SLC17A7', '9606.ENSP00000221486': 'RNASEH2A', '9606.ENSP00000221494': 'SF3A2', '9606.ENSP00000221496': 'AMH', '9606.ENSP00000221498': 'DKKL1', '9606.ENSP00000221515': 'RETN

## Part2: Map Ensembl IDs of proteins in the STRING to HGNC symbols

In [48]:
string_df = pd.read_csv("../data/STRING/9606.protein.links.v12.0.min400.onlyAB.tsv", sep="\t")
print(string_df.shape)
string_df.head()

(918440, 3)

               protein1              protein2  combined_score
0  9606.ENSP00000000233  9606.ENSP00000493357             471
1  9606.ENSP00000000233  9606.ENSP00000371175             594
2  9606.ENSP00000000233  9606.ENSP00000354878             513
3  9606.ENSP00000000233  9606.ENSP00000310226             648
4  9606.ENSP00000000233  9606.ENSP00000258098             501

In [49]:
# Map the original string df to HGNC symbols
string_mapped = string_df.copy()
string_mapped["protein1"] = string_df["protein1"].map(protein_id_to_symbol)
string_mapped["protein2"] = string_df["protein2"].map(protein_id_to_symbol)

In [50]:
# Verify the mapping
print(string_mapped.shape)
string_mapped.head()

(918440, 3)

  protein1   protein2  combined_score
0     ARF5      CYTH2             471
1     ARF5       GGA1             594
2     ARF5     KIF21A             513
3     ARF5      RAB1B             648
4     ARF5  RAB11FIP5             501

In [51]:
# Upload our filtered gene pool
gene_pool =pd.read_csv("../data/GSE252168/IG_results_v2", sep="\t", usecols=[0])
# Get the gene symbols as a list
gene_pool = list(gene_pool["Unnamed: 0"])
print(gene_pool)

['A1BG', 'RBFOX1', 'A3GALT2', 'AADAC', 'AADACL4', 'PTGES3L-AARSD1', 'AATK', 'AATK', 'ABCB9', 'ABCC10', 'ABCC4', 'ABCE1', 'ABCE1', 'ABCF2', 'ABCF2', 'ABCF3', 'ABCG1', 'ABCG4', 'ABHD10', 'ABHD14A', 'ABHD14B', 'ABHD2', 'ABHD2', 'ABHD8', 'ABLIM1', 'ABLIM1', 'ABR', 'ABR', 'ABTB1', 'ACACB', 'ACAD10', 'ACAD11', 'ACAD8', 'ACADM', 'ACAP2', 'ACAT1', 'ACAT2', 'ACBD6', 'ASIC3', 'ACCS', 'SDHAF3', 'ACOT2', 'ACOT4', 'ACOT7', 'ACOT9', 'ACOX1', 'ACPP', 'ACRBP', 'ACRC', 'ACSBG1', 'ACSL5', 'ACSS2', 'ACSS2', 'ACTB', 'ACTB', 'ACTB', 'ACTG1', 'ACTL6A', 'ACTN1', 'ACTN4', 'ACTR1B', 'ACTR5', 'ACTR6', 'ACVR1B', 'ACY1', 'ACYP1', 'ACYP2', 'ADA', 'ADAM10', 'ADAM15', 'ADAM19', 'ADAMTS1', 'ADAMTS7', 'ADAR', 'ADAR', 'ADARB1', 'ADARB1', 'ADARB2', 'ADAT1', 'ADAT2', 'ADAT3', 'ADCK1', 'COQ8B', 'ADCY9', 'ADD1', 'ADHFE1', 'ADHFE1', 'ADI1', 'ADIPOR1', 'ADIPOR1', 'ADM', 'ADNP2', 'ADPGK', 'ADSL', 'AEBP1', 'AEN', 'AES', 'AFAP1', 'AFAP1L2', 'AFF1', 'AFF4', 'AFG3L2', 'AFMID', 'AFTPH', 'AGA', 'AGFG2', 'AGGF1', 'AGK', 'AGL', 'AGMAT', 'AGPAT2', 'AGPAT2', 'AGPAT2', 'AGPAT4', 'AGPAT5', 'GPAT3', 'AGRN', 'AGTR1', 'AGTRAP', 'AGTRAP', 'PHYKPL', 'AHCTF1', 'AHCYL2', 'AHNAK', 'AHR', 'AHSA2', 'AIMP2', 'AK3', 'AKAP11', 'AKAP11', 'AKAP13', 'AKAP7', 'AKAP7', 'AKAP8', 'AKIRIN2', 'AKR1A1', 'AKR1A1', 'AKR1C2', 'AKR1C2', 'AKR1C3', 'AKT1', 'ALAS2', 'ALDH16A1', 'ALDH1A2', 'ALDH1A2', 'ALDH2', 'ALDH3B1', 'ALDH5A1', 'ALDOA', 'ALDOA', 'ALDOA', 'ALG10B', 'ALG13', 'ALG6', 'ALKBH2', 'ALKBH3', 'ALKBH4', 'ALOX12', 'ALOX5AP', 'ALPL', 'ALPPL2', 'TMEM237', 'AMACR', 'AMD1', 'AMDHD1', 'AMMECR1', 'AMOTL2', 'AMPD3', 'AMT', 'AMY1A', 'AMY2A', 'AMY2B', 'ANAPC10', 'ANAPC4', 'ANAPC5', 'ANAPC7', 'ANG', 'ANG', 'ANGEL2', 'ANK3', 'ANK3', 'ANKAR', 'ANKFY1', 'ANKH', 'ANKIB1', 'ANKMY1', 'ANKMY2', 'ANKRD10', 'ANKRD12', 'ANKRD13A', 'ANKRD20A3', 'ANKRD22', 'ANKRD22', 'ANKRD23', 'ANKRD33', 'ANKRD34C', 'ANKRD36B', 'ANKRD37', 'KANK4', 'ANKRD40', 'ANKRD44', 'ANKRD46', 'ANKRD49', 'ANKRD50', 'ANKRD52', 'ANKRD9', 'ANKS1A', 'ANKZF1', 'ANO6', 'ANO7', 'ANO8', 'ANO9', 'ANO9', 'ANP32A', 'ANP32B', 'ANP32C', 'ANTXR2', 'ANXA1', 'ANXA11', 'ANXA11', 'ANXA2P2', 'AP1G1', 'AP1G2', 'SYNRG', 'AP1M1', 'AP1S2', 'AP1S2', 'AP2A1', 'AP2B1', 'AP2S1', 'AP2S1', 'AP3D1', 'AP3M1', 'AP3M2', 'AP4B1', 'AP4E1', 'APAF1', 'APBA2', 'APBB1IP', 'APBB3', 'APC', 'APEX1', 'APH1B', 'APIP', 'APIP', 'APLF', 'APLP2', 'APOBR', 'APOBEC3A', 'APOBEC3F', 'APOBEC3F', 'APOBEC3F', 'APOL1', 'APOL3', 'APP', 'APP', 'APPL1', 'APRT', 'APRT', 'APTX', 'APTX', 'AQP1', 'AQP12B', 'AQP3', 'AQP9', 'AR', 'ARAP2', 'ARF1', 'ARF4', 'ARF4', 'ARF5', 'ARFGEF2', 'ARFRP1', 'ARGLU1', 'ARHGAP12', 'ARHGAP17', 'ARHGAP17', 'ARHGAP26', 'ARHGAP8', 'ARHGDIA', 'ARHGDIB', 'ARHGEF19', 'ARHGEF2', 'ARHGEF3', 'ARHGEF35', 'ARHGEF6', 'ARID3A', 'ARID4B', 'ARID5A', 'ARIH2', 'ARL1', 'ARL11', 'ARL15', 'ARL16', 'ARL17B', 'ARL17B', 'ARL17A', 'ARL2BP', 'ARL4A', 'ARL4A', 'ARL4A', 'ARL4C', 'ARL5A', 'ARL6IP6', 'ARMC5', 'ARMCX3', 'ARMCX6', 'ARPC1A', 'ARPC1B', 'ARPC2', 'ARPC3', 'ARPC4', 'ACTRT2', 'ARRB2', 'ARRDC2', 'ARRDC3', 'ARSA', 'ARSG', 'ART1', 'ARV1', 'AS3MT', 'ASAH1', 'ASAH2B', 'ASAP1', 'ASAP1', 'ASAP1', 'ASAP1-IT1', 'ASAP2', 'ASB13', 'ASB3', 'ASB4', 'ASB8', 'ASCC3', 'ASF1A', 'ASF1B', 'ASGR2', 'ASGR2', 'ASGR2', 'ASNS', 'ASNSD1', 'ASPHD1', 'ASS1', 'ASXL2', 'ATAD1', 'ATAD1', 'ATAD3C', 'ATAD5', 'ATF6', 'ATF7IP2', 'ATG12', 'ATG12', 'ATG16L1', 'ATG16L1', 'ATG3', 'ATG4A', 'ATG4A', 'ATG7', 'ATG9A', 'ATG9A', 'PGGHG', 'ATIC', 'ATL2', 'ATM', 'ATM', 'ATOH7', 'ATP10A', 'ATP11C', 'ATP1A1', 'ATP1B1', 'ATP1B2', 'ATP1B3', 'ATP2A2', 'ATP2B2', 'ATP2C1', 'ATP5D', 'ATP5E', 'ATP5EP2', 'ATP5F1', 'ATP5I', 'ATP5I', 'ATP5J', 'ATP5J', 'ATP5J', 'ATP5J2', 'ATP5J2', 'ATP5L', 'ATP5O', 'ATP6V0A2', 'ATP6V0B', 'ATP6V0B', 'ATP6V0D1', 'ATP6V0E2', 'ATP6V1B2', 'ATP6V1E1', 'ATP6V1G1', 'ATP6V1G2', 'CARNS1', 'ATRIP', 'ATXN1', 'ATXN1', 'ATXN1L', 'ATXN2L', 'ATXN3', 'ATXN7L2', 'AUP1', 'AURKAIP1', 'AVPR2', 'AZI2', 'AZIN1', 'B3GALT4', 'B3GLCT', 'B3GAT3', 'B3GNT8', 'B4GALT1', 'B4GALT2', 'B4GALT5', 'B4GALT7', 'B9D2', 'BAGE2', 'BAGE5', 'BAIAP2L2', 'BASP1', 'DDX39B', 'PRRC2C', 'BATF3', 'BAX', 'BAZ2B', 'BBC3', 'BBS12', 'BBS2', 'BBS2', 'BBS4', 'BBS7', 'BBS9', 'BCAP29', 'BCAP31', 'BCAS4', 'BCAS4', 'BCCIP', 'BCHE', 'BCKDHB', 'BCL11A', 'BCL2L11', 'BCL2L13', 'BCL3', 'BCL6', 'BCL9', 'BCLAF1', 'BCLAF1', 'BCLAF1', 'BCOR', 'BCORL1', 'BCR', 'BCR', 'BCR', 'BCS1L', 'BCYRN1', 'BDH1', 'BDNF', 'BEGAIN', 'BEND5', 'BEND7', 'BEX1', 'BEX2', 'BFAR', 'BIRC3', 'BIRC3', 'BIVM', 'BLK', 'BLOC1S2', 'BLZF1', 'BMI1', 'BMP2K', 'BMP2K', 'BMP8B', 'BMS1', 'BMX', 'BNIP1', 'BNIP2', 'BNIP3', 'BNIP3L', 'BNIPL', 'BOLA2', 'BOLA2', 'BOLA2', 'BOLA3', 'BOLA3', 'BOP1', 'BPHL', 'BPTF', 'BRD3', 'BRD4', 'BRD9', 'BRF1', 'BRI3', 'BRI3BP', 'BRSK1', 'CELF4', 'CELF6', 'WDR11', 'BRWD3', 'BSG', 'BTAF1', 'ZBTB44', 'BTBD6', 'BTBD7', 'BTG3', 'BTLA', 'BTLA', 'BTN2A2', 'BTN3A1', 'BTNL3', 'BTNL8', 'BUB3', 'TSPOAP1', 'TSPO2', 'BZW2', 'C10orf105', 'FUOM', 'EDRF1', 'BORCS7', 'BORCS7', 'C10orf35', 'PROSER2', 'C10orf54', 'RNLS', 'RNLS', 'VSTM4', 'OLMALINC', 'FAM204A', 'C11orf1', 'TMEM258', 'LMNTD2', 'ARL14EP', 'LAMTOR1', 'IFT46', 'C11orf63', 'C11orf68', 'HIKESHI', 'C11orf74', 'C11orf80', 'UQCC3', 'METTL25', 'C12orf29', 'NAA25', 'RHNO1', 'C12orf4', 'KANSL2', 'C12orf43', 'RITA1', 'C12orf57', 'C12orf65', 'RGCC', 'KIAA0226L', 'BORA', 'NRDE2', 'MIS18BP1', 'COX16', 'SDR39U1', 'GSKIP', 'VCPKMT', 'GON7', 'EFCAB11', 'SPTSSA', 'SLIRP', 'C14orf159', 'DHRS4-AS1', 'SAMD15', 'IFT43', 'IGBP1P1', 'C14orf2', 'C14orf28', 'IRF2BPL', 'ELMSAN1', 'BBOF1', 'LINC01550', 'FAM219B', 'KNSTRN', 'C15orf39', 'C15orf48', 'C15orf57', 'C15orf57', 'HYPK', 'TMEM204', 'SNRNP25', 'ENKD1', 'CDIP1', 'USB1', 'C16orf58', 'CMC2', 'FOPNL', 'METTL22', 'MEIOB', 'BRICD5', 'CFAP20', 'OGFOD3', 'GID4', 'TEFM', 'ADPRM', 'TEPSIN', 'C17orf58', 'MILR1', 'TMEM256', 'FAM222B', 'FAAP100', 'SMG8', 'ELP5', 'SCIMP', 'OXLD1', 'METTL23', 'C17orf96', 'C18orf25', 'TIMM21', 'C19orf12', 'R3HDM4', 'C19orf25', 'C19orf38', 'C19orf48', 'C19orf48', 'WDR83OS', 'MCEMP1', 'C19orf60', 'SMG9', 'C1GALT1C1', 'DIEXF', 'C1orf112', 'C1orf115', 'C1orf122', 'SPRTN', 'MEAF6', 'MINOS1', 'C1orf159', 'COA7', 'FAM212B', 'TSEN15', 'LURAP1', 'C1orf198', 'ATP1A1-AS1', 'C1orf21', 'C1orf210', 'C1orf229', 'FAM129A', 'COA6', 'THEMIS2', 'HSPB11', 'TEX35', 'C1orf52', 'C1orf54', 'HENMT1', 'RSRP1', 'RRNAD1', 'C1QB', 'C1QBP', 'C1QC', 'C1QL2', 'C1QTNF6', 'C1R', 'C1RL', 'FAM209A', 'FAM209B', 'NOL4L', 'BPIFB1', 'DZANK1', 'FAM65C', 'FAM217B', 'C20orf196', 'C20orf197', 'ZFAS1', 'MRGBP', 'C20orf24', 'C20orf24', 'C20orf24', 'TMEM230', 'RTFDC1', 'ROMO1', 'NDUFAF5', 'NDUFAF5', 'ARHGAP40', 'C21orf2', 'C21orf33', 'MIR99AHG', 'SMIM11A', 'C21orf59', 'PAXBP1', 'FAM207A', 'C21orf91', 'MORC2-AS1', 'RTCB', 'SMDT1', 'C22orf39', 'KIAA0930', 'C2CD2', 'C2CD2L', 'ERLEC1', 'CAMKMT', 'WDCP', 'C2orf49', 'NDUFAF7', 'C2orf57', 'CLHC1', 'COA5', 'PRADC1', 'PTRHD1', 'C2orf88', 'TRABD2A', 'C3AR1', 'C3orf18', 'TAMM41', 'CEP19', 'C3orf36', 'HMCES', 'POMGNT2', 'C3orf62', 'FAM208A', 'ARIH2OS', 'FOXL2NB', 'ELP6', 'ELP6', 'ELP6', 'C4BPA', 'TRMT44', 'PACRGL', 'C4orf33', 'SMIM14', 'TRAPPC11', 'C4orf48', 'C5AR1', 'NREP', 'C5orf15', 'DCANP1', 'FAM172A', 'TMEM267', 'CYSTM1', 'C5orf34', 'POC5', 'ANXA2R', 'SMIM3', 'C6', 'ADTRP', 'DNPH1', 'PNISR', 'UQCC2', 'CCDC167', 'OARD1', 'SNHG5', 'SMIM8', 'TBC1D32', 'THEMIS', 'SLC18B1', 'SAPCD1', 'C6orf47', 'C6orf48', 'ERMARD', 'SLC22A23', 'TMEM243', 'YAE1D1', 'FAM200A', 'SNHG15', 'PPP1R35', 'C7orf49', 'HILPDA', 'C8orf33', 'NDUFAF6', 'SMIM19', 'MCMDC2', 'C8orf58', 'C8orf59', 'TRIQK', 'ERCC6L2', 'C9orf106', 'SPOUT1', 'SWI5', 'TMEM261', 'TMEM8B', 'TRMO', 'CYSRT1', 'C9orf40', 'UAP1L1', 'C9orf72', 'C9orf72', 'C9orf85', 'NAIF1', 'CA11', 'CA2', 'CA4', 'CABLES2', 'CACNA2D3', 'CADM3', 'CADPS2', 'CALB2', 'CALCOCO2', 'CALN1', 'CALR', 'CAMK1D', 'CAMK1D', 'CAMK2B', 'CAMLG', 'CAND1', 'CANT1', 'CANX', 'CAP1', 'CAPN1', 'CAPN11', 'CAPN12', 'CAPN3', 'CAPN3', 'CAPNS1', 'CAPRIN1', 'CAPRIN2', 'CAPRIN2', 'CAPS', 'CAPSL', 'CAPZB', 'CARD14', 'CARD16', 'CARD17', 'CARHSP1', 'NAXD', 'CARM1', 'CASP3', 'CASP3', 'CASP7', 'CASQ2', 'CATSPER4', 'CAV2', 'CBL', 'CBLN3', 'CBR4', 'CBX3', 'CBX4', 'CBY1', 'CBY3', 'SGF29', 'CCDC106', 'MCUB', 'PRIMPOL', 'CCDC12', 'CCDC125', 'PPP1R21', 'CCDC130', 'VPS50', 'CCDC14', 'CCDC144A', 'CCDC15', 'CCDC18', 'CCDC25', 'CCDC34', 'CCDC36', 'CEP83', 'CEP95', 'EFCC1', 'HAUS1', 'CCDC51', 'CCDC53', 'CCDC59', 'CCDC60', 'CCDC65', 'CCDC66', 'CCDC69', 'CCDC7', 'CCDC71', 'TMA7', 'TRMT13', 'CCDC84', 'CCDC86', 'CCDC90B', 'SPDL1', 'CCL3L1', 'CCNB1IP1', 'CCNC', 'CCND3', 'CCNDBP1', 'CCNE1', 'CCNG2', 'CCNI', 'CCNL1', 'CCNT2', 'CCNY', 'CCPG1', 'CCR2', 'CCR6', 'CCR7', 'CCR9', 'CDK20', 'CCT2', 'CCT4', 'CCT5', 'CCT6P1', 'CCT7', 'CD14', 'CD14', 'CD160', 'CD163', 'CD163', 'CD177', 'CD19', 'CD2', 'CD200R1', 'CD200R1L', 'CD22', 'CD226', 'CD244', 'CD247', 'CD27', 'CD274', 'CD28', 'CD300C', 'CD300LF', 'CD302', 'CD38', 'CD3D', 'CD3D', 'CD3D', 'CD40LG', 'CD44', 'CD47', 'CD52', 'CD68', 'CD68', 'CD69', 'CD72', 'CD79A', 'CD79B', 'CD79B', 'CD80', 'CD82', 'CD82', 'CD83', 'CD83', 'CD9', 'CD96', 'ADGRE5', 'CD99', 'CD99L2', 'CDA', 'CDC14A', 'CDC14A', 'CDC16', 'CDC16', 'CDC23', 'CDC34', 'CDC40', 'CDC42', 'CDC42BPB', 'CDC42EP2', 'CDH2', 'CDH23', 'CDIPT', 'CDK10', 'CDK2AP1', 'CDK4', 'CDK5RAP1', 'CDK5RAP2', 'CDK5RAP3', 'CDK5RAP3', 'CDKN2D', 'CDR2', 'CDS2', 'CDYL2', 'CEACAM1', 'CEACAM1', 'CEACAM4', 'CEBPA', 'CEBPB', 'CEBPD', 'CEBPG', 'CECR5', 'CECR6', 'CENPK', 'CENPM', 'CENPT', 'CENPV', 'ARAP1', 'CNTRL', 'CEP135', 'CEP170', 'CEP250', 'HAUS2', 'CEP350', 'CEP70', 'CEP76', 'CEP78', 'CEPT1', 'CERK', 'CES2', 'CETN1', 'CETP', 'CETP', 'CFDP1', 'CFL1', 'CFL2', 'CFLAR', 'CFP', 'CGB2', 'CGGBP1', 'CHCHD4', 'CHCHD7', 'COA4', 'CHD1L', 'CHD3', 'CHD9', 'CHI3L2', 'CHIC2', 'CHKA', 'CHKB', 'CHKB', 'CHM', 'CHMP1A', 'CHMP2A', 'CHMP2A', 'CHMP5', 'CHMP5', 'CHMP5', 'CHMP7', 'CHN1', 'CHP1', 'CHRNA2', 'CHRNB1', 'CHST15', 'CHTF18', 'CIAO1', 'CIAPIN1', 'CIB2', 'CIDEA', 'SARNP', 'UTP4', 'CITED2', 'CIZ1', 'CKAP2L', 'CKAP4', 'CKB', 'CKLF', 'CKS1B', 'CKS1B', 'CKS2', 'CKS2', 'CLASP1', 'CLC', 'CLCC1', 'CLCF1', 'CLCN3', 'CLCN7', 'CLDN15', 'CLDND1', 'CLDND1', 'CLEC12A', 'CLEC2B', 'CLEC2D', 'CLEC4E', 'CLEC7A', 'CLEC7A', 'CLECL1', 'CLK1', 'CLK4', 'CLN5', 'CLN8', 'CLNS1A', 'CLOCK', 'CLP1', 'CLPX', 'CLRN1', 'CLSTN1', 'CLTCL1', 'CLYBL', 'CLYBL', 'CMIP', 'CMPK1', 'CMTM3', 'CMTM4', 'CMTM4', 'CMTM5', 'CNGB1', 'CNN2', 'CNNM4', 'CNOT1', 'CNOT7', 'CNPY2', 'CNPY4', 'CNR1', 'CNR2', 'CNTN5', 'CNTNAP1', 'CNTNAP2', 'COBLL1', 'COG5', 'COG5', 'COG6', 'COIL', 'COL11A1', 'COL6A5', 'COL6A2', 'COL9A2', 'COLQ', 'COMMD10', 'COMMD3', 'COMMD5', 'COMMD6', 'COMMD7', 'COMMD8', 'COMT', 'COPB1', 'COPE', 'COPE', 'COPG2', 'COPS3', 'COPS4', 'COPS5', 'COPS7B', 'COPS8', 'COQ10A', 'COQ2', 'COQ3', 'COQ5', 'COQ7', 'COQ9', 'CORO2A', 'COTL1', 'COX19', 'COX6A1', 'COX6B2', 'COX6C', 'COX7A2', 'COX7A2L', 'COX7B', 'COX7C', 'CPEB3', 'CPN2', 'CPNE1', 'CPOX', 'CPSF4', 'CPT1B', 'CPT2', 'CR1', 'CR1', 'CRADD', 'CRAT', 'CRBN', 'CREBBP', 'CREBBP', 'CREBZF', 'CRELD1', 'CRELD1', 'CRIP2', 'CRIPAK', 'CRISPLD2', 'CRK', 'CRK', 'CRK', 'CRKL', 'CRLS1', 'LUC7L3', 'LUC7L3', 'CROT', 'MED17', 'MED7', 'CRTAP', 'CRYGC', 'CRYGS', 'CRYZ', 'YBX3', 'CSE1L', 'CSE1L', 'CSF2RA', 'CSF2RA', 'CSF2RB', 'CSF3R', 'CSMD1', 'CSNK1A1', 'CSNK1A1', 'CSNK1D', 'CSNK1E', 'CSNK2B', 'CSRNP2', 'CSRP1', 'KAT14', 'CST7', 'CSTF2T', 'CSTF3', 'CSTF3', 'CSTF3', 'CT47A6', 'CT47A7', 'CT47A7', 'CTAGE5', 'CTAGE6', 'CTBS', 'CTDP1', 'AGAP6', 'CTH', 'CTLA4', 'CTLA4', 'CTNNA1', 'CTNNAL1', 'CTNS', 'CTPS1', 'CTPS2', 'CTPS2', 'CTSA', 'CTSC', 'CTSD', 'CTSE', 'CTSF', 'CTSG', 'CTSK', 'CTSZ', 'CTTN', 'CUBN', 'CUEDC2', 'CELF2', 'CELF2', 'CUL5', 'CUL9', 'CUTC', 'CUX1', 'CWC15', 'CWF19L2', 'CXCL10', 'CXCL16', 'CXCL3', 'CXCL5', 'CXCR1', 'CXCR3', 'CXCR4', 'CXCR6', 'CXorf40B', 'ALG13', 'CXorf57', 'CXorf65', 'CXXC5', 'CYB561', 'CYB5A', 'CYB5R1', 'CYB5R3', 'CYB5R3', 'CYBA', 'CYB561A3', 'CYBB', 'CYFIP1', 'CYP2D7', 'CYP2R1', 'CYP2U1', 'CYP4F12', 'CYP4F3', 'CYP4F3', 'CYP4V2', 'SPECC1', 'D2HGDH', 'DAB2', 'DAB2', 'DAG1', 'DALRD3', 'DAP', 'DAP3', 'DAPK2', 'DAZ4', 'DAZAP1', 'DAZAP2', 'DBI', 'DBNL', 'DBNL', 'DBT', 'DCAF10', 'DCAF6', 'DCAF7', 'DCBLD2', 'DCLK1', 'DCLK3', 'DCLRE1C', 'DCLRE1C', 'DCP2', 'DCTN6', 'DCUN1D2', 'DCUN1D3', 'DCUN1D4', 'DCUN1D4', 'DCUN1D5', 'DDA1', 'DDB1', 'DDIT3', 'DDTL', 'DDX1', 'DDX10', 'DDX18', 'DDX19A', 'DDX19B', 'DDX31', 'DDX39A', 'DDX46', 'DDX47', 'DDX5', 'DDX50', 'DDX51', 'DDX54', 'DDX55', 'DEAF1', 'DEDD2', 'DEFB114', 'DEFB130', 'EXO5', 'EXO5', 'DENND1C', 'DENND2D', 'DENND4B', 'DENND4C', 'DENR', 'DENR', 'DEPDC5', 'DERA', 'DERL2', 'DERL3', 'DGAT2', 'DGCR11', 'DGKQ', 'DGKZ', 'DHDDS', 'DHRS11', 'DHRS13', 'DHRS4', 'DHRS7', 'DHX16', 'DHX29', 'DHX32', 'DHX40', 'DIDO1', 'DIDO1', 'DIMT1', 'DIO1', 'DIO2', 'DIP2A', 'DIRC2', 'DIS3L', 'DISC1', 'DISP1', 'RRP7BP', 'DKC1', 'POM121L9P', 'POTEC', 'TMEM132C', 'DKK3', 'DLEC1', 'DLK2', 'DMAP1', 'DMD', 'DMP1', 'DMTF1', 'DMTF1', 'DNA2', 'DNAH1', 'DNAJA1', 'DNAJA3', 'DNAJB11', 'DNAJB12', 'DNAJB12', 'DNAJB9', 'DNAJC10', 'DNAJC11', 'DNAJC13', 'DNAJC19', 'DNAJC21', 'DNAJC25', 'DNAJC27', 'DNAJC30', 'DNAJC30', 'DNAJC7', 'DNAJC8', 'DNAJC9', 'DNAL4', 'DNASE1L1', 'DNASE1L1', 'DNHD1', 'DNM3', 'DNMT1', 'DNTTIP1', 'DOCK10', 'DOCK2', 'DOK1', 'DOK3', 'DOPEY1', 'DOT1L', 'DPCR1', 'DPH2', 'DPH5', 'DPH5', 'DPM1', 'DPP3', 'DPP6', 'DPP8', 'DPP8', 'DPRXP4', 'DPY30', 'DPYD', 'DPYSL5', 'DTNBP1', 'DTWD1', 'DTWD2', 'DTX1', 'DTX2', 'DTX3', 'DTX3L', 'CTDNEP1', 'DUS3L', 'DUSP1', 'DUSP12', 'DUSP14', 'DUSP18', 'DUSP26', 'DUSP5', 'DUSP6', 'DUT', 'DUT', 'DUT', 'DUX1', 'DUX3', 'DVL2', 'DYNC1I2', 'DYNC1LI2', 'DYNLRB1', 'DYNLT3', 'DYRK2', 'DYRK4', 'DYSF', 'E2F1', 'E2F6', 'EAPP', 'EARS2', 'GPR183', 'GPR183', 'EBNA1BP2', 'EBPL', 'ECE1', 'ECHDC2', 'ECHDC3', 'EDEM2', 'EDEM3', 'EDNRB', 'EEF1A1', 'EEF1A1', 'EEF1A1', 'EEF1A1', 'EEF1B2', 'EEF1B2', 'EEF1B2', 'EEF1B2', 'EEF1E1', 'EFEMP2', 'EFHD2', 'EFNA2', 'EFR3A', 'EFL1', 'EGLN1', 'EGR1', 'EHD1', 'EHD2', 'EIF1', 'EIF1AX', 'EIF1B', 'EIF2A', 'EIF2AK2', 'EIF2AK4', 'EIF2B4', 'EIF2B5', 'EIF2S1', 'EIF2S2', 'EIF3D', 'EIF3E', 'EIF4A1', 'EIF4A2', 'EIF4B', 'EIF4E2', 'EIF4E3', 'EIF4E3', 'EIF4EBP2', 'EIF4G2', 'EIF4G2', 'EIF5A2', 'CELA1', 'ELANE', 'ELAVL1', 'ELAVL3', 'ELK3', 'ELL', 'ELMO1', 'ELMO3', 'ELOVL1', 'ELP2', 'EMG1', 'EML2', 'EML4', 'ADGRE3', 'ADGRE4P', 'EMX2OS', 'ENDOD1', 'ENHO', 'ENHO', 'ENO2', 'ENO3', 'ENOPH1', 'ENOSF1', 'ENOX2', 'ENPP4', 'ENPP7', 'ENSA', 'ENSA', 'ENTPD8', 'ENY2', 'EOMES', 'EPB41', 'EPB41L3', 'EPB41L4A', 'EPB41L5', 'EPC1', 'EPHA1', 'EPHA10', 'EPHA10', 'EPHX2', 'EPM2A', 'EPM2AIP1', 'EPN2', 'EPN2', 'EPRS', 'EPS15', 'ERCC3', 'ERCC5', 'ERGIC1', 'ERH', 'ERICH1', 'ERMN', 'ERMP1', 'ERP27', 'ERVW-1', 'ESAM', 'ETF1', 'ETFB', 'ETFB', 'ETV2', 'ETV6', 'EVI2A', 'EVI2B', 'EVI5', 'EVL', 'EXD3', 'EXOC4', 'EXOC7', 'EXOSC1', 'EXOSC1', 'EXOSC10', 'EXOSC2', 'EXOSC7', 'EYS', 'F11R', 'F13A1', 'F2R', 'F5', 'F8A1', 'FADD', 'FAH', 'FAHD2B', 'FAIM', 'FCMR', 'UBALD2', 'FAM101B', 'FAM102A', 'FAM103A1', 'FAM104B', 'ST13P4', 'ST13P4', 'FAM111A', 'FAM111A', 'PCED1A', 'FAM114A2', 'DENND6B', 'FAM117B', 'FAM120C', 'FAM122B', 'AMER1', 'FAM126B', 'MZT2A', 'FAM129A', 'FAM129C', 'FAM131A', 'FAM131B', 'FAM133B', 'FAM134B', 'FAM136A', 'FAM13A-AS1', 'FAM156A', 'FAM156A', 'FAM156B', 'EMC9', 'FAM159A', 'SMIM11A', 'FAM173B', 'EVA1B', 'FAM177A1', 'FAM177A1', 'SLF2', 'FAM188A', 'CCSER2', 'MCRIP2', 'FAM21C', 'FAM24A', 'FAM24B', 'COX20', 'WASH3P', 'WASH3P', 'FAM3C', 'STRIP1', 'STRIP2', 'FAM43A', 'BOD1', 'SUPT20H', 'SUPT20H', 'FAM49A', 'FAM53C', 'FAM58A', 'BRINP3', 'FAM60A', 'ESYT2', 'FAM65A', 'FAM65B', 'FAM69A', 'TMEM255A', 'FAM72B', 'MIGA1', 'MIGA1', 'SPATA31C1', 'FAM76B', 'FAM83F', 'FAM84B', 'FAM86B1', 'FAM89A', 'FAM89B', 'FAM91A1', 'FAM96A', 'FAM98A', 'FAM98B', 'FAM98C', 'FANCD2', 'FANCE', 'FANCG', 'FAR1', 'FAR2', 'FAR2', 'FARS2', 'FARSB', 'FASLG', 'FASTK', 'FASTK', 'FASTKD1', 'FASTKD2', 'FAU', 'FBL', 'FBLIM1', 'FBLN2', 'FBLN7', 'FBP1', 'KDM2B', 'FBXL18', 'FBXL20', 'FBXL5', 'FBXO11', 'FBXO15', 'FBXO18', 'FBXO22', 'FBXO31', 'FBXO4', 'FBXO44', 'FBXO44', 'FBXO6', 'FBXW11', 'FBXW9', 'FCER1A', 'FCER1G', 'FCER2', 'FCF1', 'FCGBP', 'FCGR2A', 'FCGR2A', 'FCGR2A', 'FCGR3B', 'FCGRT', 'FCHSD1', 'FCN1', 'FCRL3', 'FCRL5', 'FCRLB', 'FDPSP2', 'FDXACB1', 'FECH', 'FERMT3', 'FES', 'FEZ1', 'FFAR2', 'FGF23', 'FGFR1OP', 'FGR', 'FH', 'FHL1', 'FHL2', 'FIBP', 'FIGNL1', 'FKBP1A', 'FKBP1A', 'FKBP1B', 'FKBP5', 'FKRP', 'FLAD1', 'FLCN', 'FLII', 'BIN3-IT1', 'CCNJL', 'PRR5L', 'GIN1', 'SLC48A1', 'CPED1', 'C11orf80', 'PLBD1', 'CCDC155', 'ANKRD18A', 'TEX19', 'ZNF815P', 'LINC00921', 'AMER1', 'TCAF2', 'FLJ44635', 'TMPPE', 'TMPPE', 'LVRN', 'TMEM259', 'FLOT1', 'FLOT2', 'FLT3LG', 'FLVCR2', 'FMNL1', 'FMNL3', 'FMO1', 'FMO2', 'FMO3', 'FNBP4', 'FNDC3A', 'FNIP2', 'FNTB', 'FOS', 'FOSB', 'FOXC2', 'FOXD4', 'FOXD4L1', 'FOXJ2', 'FOXN2', 'FOXO1', 'FOXO3', 'FOXP1', 'FOXRED1', 'FPR1', 'FPR2', 'FPR2', 'MTOR', 'FRAT1', 'FRAT2', 'FRMD3', 'FRRS1', 'FRYL', 'FSCB', 'FSCN1', 'FSTL4', 'FTH1', 'FTH1P3', 'FTL', 'MRM2', 'FTSJ3', 'CMTR2', 'FUBP3', 'FUK', 'FUT6', 'FUT7', 'FXR1', 'FXR1', 'FXYD1', 'FXYD2', 'FYB', 'FYN', 'FYN', 'FZD10', 'G3BP2', 'G6PD', 'G6PD', 'GAB2', 'GABARAP', 'GABARAPL2', 'GABBR1', 'GABPB2', 'GADD45A', 'GADD45A', 'GADD45G', 'GAL3ST4', 'GALK2', 'GALNT11', 'GALNT9', 'GALT', 'GAMT', 'GAPDH', 'GAPDH', 'GAPDH', 'GAS6', 'GAS6', 'GAS7', 'GATA3', 'GATAD1', 'GATAD2A', 'GATAD2B', 'GBA', 'GBA', 'GBA2', 'GBAS', 'GBGT1', 'GCSAM', 'GCH1', 'GCLC', 'GCLM', 'GCLM', 'MYZAP', 'GCSH', 'GCSH', 'GDE1', 'GDF1', 'GDPD1', 'GEMIN4', 'GEMIN6', 'GEN1', 'GFI1B', 'GFM2', 'GGNBP2', 'GGPS1', 'GIMAP1', 'GIMAP2', 'GIMAP2', 'GIMAP5', 'GIMAP7', 'GIN1', 'GINS2', 'GIT2', 'SLX1A', 'GJB6', 'GKAP1', 'GLA', 'GLB1', 'GLB1', 'GLCE', 'GLIPR1', 'GLIPR2', 'GLIS2', 'GLMN', 'GLO1', 'GLRX', 'GLRX3', 'GLRX5', 'GLT1D1', 'GLTP', 'GLTSCR1', 'GLUD1', 'GLUL', 'GLYATL2', 'GLYCTK', 'GMFB', 'GNA15', 'GNAI2', 'GNAL', 'GNAQ', 'GNAS', 'GNAT1', 'GNAZ', 'GNB1L', 'GNB2', 'GNB5', 'GNG5', 'GNL3', 'GNL3', 'GNL3L', 'GNPAT', 'GNPDA2', 'GNRH1', 'GNS', 'GOLGA1', 'GOLGA7', 'GOLGA7B', 'GOLGA8A', 'GOLGA8B', 'GOLIM4', 'GOLT1B', 'GOPC', 'GOT1', 'GP1BA', 'GP6', 'GP9', 'GPATCH2', 'GPATCH4', 'GPC2', 'GPC4', 'GPC6', 'GPD1L', 'GPN1', 'GPR1', 'GPR108', 'HCAR3', 'HCAR3', 'ADGRG4', 'ADGRG7', 'GPR141', 'GPR146', 'GPR18', 'GPR180', 'GPR83', 'GPR84', 'GPR89B', 'ADGRG3', 'ADGRG3', 'ADGRG3', 'GPRIN3', 'GPSM3', 'GPX7', 'GPX8', 'GRAMD1A', 'GRAMD4', 'GRAP2', 'GRASP', 'GRB10', 'GRB14', 'GRB14', 'GRB2', 'GRB2', 'GRIK1', 'GRIN1', 'GRIN3A', 'GRINA', 'GRIPAP1', 'GRM3', 'GRN', 'GRN', 'GRSF1', 'GRXCR2', 'GSDMA', 'GSDMB', 'GSDMB', 'GSDMB', 'GSK3B', 'GSPT2', 'GSR', 'GSR', 'GSS', 'GSTA3', 'GSTM2', 'GSTM4', 'GSTTP2', 'GSTTP2', 'GSTZ1', 'GTDC1', 'GTF2B', 'GTF2E1', 'GTF2E2', 'GTF2F1', 'GTF2F2', 'GTF2H1', 'GTF3A', 'GTF3C2', 'GTF3C3', 'GTF3C5', 'GTPBP3', 'GUCA1B', 'GUCA2A', 'GUCY2F', 'GXYLT1', 'GYG1', 'GYG2', 'GYPB', 'GYPC', 'GYPC', 'GYPE', 'GZMA', 'GZMB', 'GZMK', 'GZMM', 'H1F0', 'H2AFJ', 'H2AFY', 'H2AFY2', 'H3F3A', 'H3F3A', 'H3F3A', 'HABP4', 'HACL1', 'HADH', 'HADHB', 'HAPLN3', 'HAT1', 'HBQ1', 'HBS1L', 'HBZ', 'HCCS', 'HCFC1R1', 'HCG22', 'HCK', 'HCN4', 'HDAC5', 'HDDC2', 'HDDC3', 'HDHD2', 'HDHD3', 'HEATR1', 'HEATR5B', 'HEBP1', 'HECA', 'HECTD1', 'HECTD2', 'HELB', 'HELQ', 'HELZ', 'HEMGN', 'HEMGN', 'HEPACAM2', 'HERC2', 'HERC4', 'HERPUD2', 'HERPUD2', 'HES6', 'HEXDC', 'HGF', 'HIF1AN', 'HIGD1A', 'HINFP', 'HINT1', 'HINT3', 'HIP1', 'HIP1R', 'UBE2K', 'HIPK2', 'HIST1H2AG', 'HIST1H2BC', 'HIST1H2BE', 'HIST1H2BH', 'HIST1H2BJ', 'HIST1H2BK', 'HIST1H2BK', 'HIST1H2BO', 'HIST1H3F', 'HIST1H3H', 'HIST1H4H', 'HIST2H2AA3', 'HIST2H2AA3', 'HIST2H2AA4', 'HIST2H2AC', 'HIST2H2BE', 'HIST2H3C', 'HIVEP2', 'HIVEP3', 'HK1', 'HK2', 'HLA-A', 'HLA-DMB', 'HLA-DOB', 'HLA-DRA', 'HLA-E', 'HLCS', 'HLTF', 'HLX', 'HM13', 'HMG20A', 'HMGB1', 'HMGB2', 'HMGB2', 'HMGCLL1', 'HMGCS1', 'HMGN2', 'HMGN4', 'HMOX1', 'HN1', 'HNMT', 'HNMT', 'HNRNPA1', 'HNRNPA2B1', 'HNRNPA3', 'HNRNPAB', 'HNRNPC', 'HNRNPCL1', 'HNRNPF', 'HNRNPH1', 'HNRNPH2', 'HNRNPK', 'HNRNPK', 'HNRNPR', 'HNRNPU', 'HNRNPU', 'HNRNPUL1', 'HNRNPA1P10', 'HNRNPDL', 'HNRNPK', 'HOOK1', 'HOPX', 'HOXC4', 'HOXC6', 'HP', 'HPCAL1', 'HPS4', 'HPS5', 'HPSE', 'AGFG1', 'HRH2', 'RIDA', 'LINC00570', 'SMAD9', 'INTS6-AS1', 'DENND1B', 'UHMK1', 'ZNF597', 'LOC102724002', 'LOC105378397', 'VPS13A', 'DCUN1D5', 'LOC102467216', 'FAM53A', 'FAM212B', 'HMBOX1', 'LINC

In [ ]:
# Filter the mapped STRING df for our filtered gene pool
string_mapped_filt = string_mapped[string_mapped["protein1"].isin(gene_pool)]
string_mapped_filt = string_mapped[string_mapped["protein2"].isin(gene_pool)]

In [55]:
# Check the final STRING df size
print(string_mapped_filt.shape)
string_mapped_filt.head()

(270493, 3)

   protein1  protein2  combined_score
3      ARF5     RAB1B             648
6      ARF5     RAB6A             415
9      ARF5      GNB2             563
12     ARF5  MAPK8IP3             451
21     ARF5    KDELR2             581

In [ ]:
# # Save the final filtered version of STRING
# string_mapped_filt.to_csv("../data/STRING/PPI_filtered.tsv", sep="\t", index=False)

## Part 3: Construct filtered PPI via Network X

In [4]:
PPI_df = pd.read_csv("../data/STRING/PPI_filtered.tsv", sep="\t")

In [ ]:
for _, row iteerorws

In [ ]:
# # Check the overall PPI size
# print(f"The number of nodes in the PPI: {nx.number_of_nodes(G)}")
# print(f"The number of nodes in the PPI: {nx.number_of_edges(G)}")

The number of nodes in the PPI: 16733
The number of nodes in the PPI: 270493